image: berenger/spetabaruci

simple-debug:
  script:
    - mkdir build
    - cd build
    - CXX=g++-8 cmake -DUSE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug  ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test

simple-release:
  script:
    - mkdir build
    - cd build
    - CXX=g++-8 cmake -DUSE_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test


coverage:
  script:
    - mkdir build
    - cd build
    - CXX=g++-8 cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_COVERAGE=ON -DUSE_TESTING=ON -DUSE_SIMU_TESTING=ON ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=TRUE make test
    - /usr/local/bin/lcov --gcov-tool /usr/bin/gcov-8 --directory CMakeFiles/ --directory unit-tests/CMakeFiles/ -c -o coverage-rapport.info
    - /usr/local/bin/lcov --gcov-tool /usr/bin/gcov-8 --list coverage-rapport.info
    - /usr/local/bin/genhtml -o ../coverage -t "Coverage example" coverage-rapport.info
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - example-full-coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master


